os:
  - linux
  - osx

language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      
  allow_failures:
    - rust: nightly
  fast_finish: true
