[package]
name = "scavenger"
version = "1.0.0-beta"
authors = ["PoC Consortium <bots@cryptoguru.org>"]
description = """
scavenger is a cryptominer for the currency burstcoin
"""
build = "build.rs"
repository = "https://github.com/PoC-Consortium/scavenger"
documentation = "https://github.com/PoC-Consortium/scavenger"
keywords = ["burstcoin", "miner", "rust","cryptocurrency"]
readme = "README.md"

[dependencies]
hyper = "0.12"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
libc = "0.1"
hex = "0.3.1"
tokio = "0.1"
tokio-core = "0.1"
url = "1.7.1"
chan = "0.1.21"
futures = "0.1.22"
rayon = "1.0"
num_cpus = "0.2"
sys-info = "*"
stopwatch = "0.0.7"
cfg-if = "0.1"
filetime = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["fileapi"] }

[build-dependencies]
cc = "1.0"